name: norminette

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v3
    - uses: alexandregv/norminette-action@v3
      with:
        flags: "ft_printf.c ft_printf_utils.c ft_printf.h"