name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: tester
      run: cc ft_printf.c ft_printf_utils.c tester.c 2>/dev/null && ./a.out
